// Shared product data used across all pages
export const PRODUCTS = [
  {
    id: "shaghaf",
    name: "Shaghaf",
    arabic: "شغف",
    subtitle: "Hydrating & Frizz Control",
    tagline: "Fuel Your Passion",
    purpose: "Hydration",
    price: 39,
    image: "/assets/product-1.jpeg",
    accent: "#5a6b47",
    bg: "#eef0ea",
    description:
      "Shaghaf is our signature hydrating formula, blended from cold-pressed Argan and pure Jojoba oil. It penetrates deeply to tame frizz and deliver all-day moisture without any greasy residue.",
    ingredients: ["Argan Oil", "Jojoba Oil", "Sweet Almond Oil", "Vitamin E", "Cedarwood Essential Oil"],
    howToUse: "Apply 3-5 drops to palm, rub hands together, then work through dry or damp beard from root to tip. Use daily after cleansing.",
    scent: "Warm Cedar & Sandalwood with earthy undertones.",
    size: "30ml",
    stock: true,
  },
  {
    id: "roab",
    name: "Ro'ab",
    arabic: "رُعب",
    subtitle: "Follicle Growth Support",
    tagline: "Command Respect",
    purpose: "Growth",
    price: 39,
    image: "/assets/product-2.jpeg",
    accent: "#4a4a4a",
    bg: "#ebebeb",
    description:
      "Ro'ab stimulates dormant follicles using a powerful blend of Castor and Rosemary oil. Designed for men serious about achieving a fuller, thicker beard.",
    ingredients: ["Castor Oil", "Rosemary Oil", "Biotin Complex", "Black Seed Oil", "Peppermint Oil"],
    howToUse: "Massage 4-6 drops into the beard and underlying skin using fingertips. Leave on overnight for maximum penetration. Use 4-5 times per week.",
    scent: "Fresh Mint & Herbs with a cool finish.",
    size: "30ml",
    stock: true,
  },
  {
    id: "addawa",
    name: "Ad'Dawa",
    arabic: "الدواء",
    subtitle: "Healing & Itch Relief",
    tagline: "The Remedy",
    purpose: "Healing",
    price: 39,
    image: "/assets/product-3.jpeg",
    accent: "#c8a45e",
    bg: "#f5eddc",
    description:
      "Ad'Dawa is the remedy. Formulated with anti-inflammatory Tea Tree and Calendula extract, it eliminates beardruff, soothes irritation, and heals the skin beneath the beard.",
    ingredients: ["Tea Tree Oil", "Calendula Extract", "Chamomile Oil", "Aloe Vera", "Lavender Oil"],
    howToUse: "Apply 3-4 drops directly to itchy or flaky areas. Massage gently into skin. Use twice daily until irritation subsides, then maintain with 3x per week.",
    scent: "Clean Floral & Herbal with a calming softness.",
    size: "30ml",
    stock: true,
  },
  {
    id: "qawwam",
    name: "Qawwam",
    arabic: "قوّام",
    subtitle: "Strength & Structure",
    tagline: "For Alpha Males",
    purpose: "Strength",
    price: 45,
    image: "/assets/product-4.jpeg",
    accent: "#1a1a1a",
    bg: "#d6d4cf",
    description:
      "Qawwam is our most powerful formula, engineered for strength. A potent blend of Black Seed oil and Pumpkin Seed strengthens each strand from the root, reducing breakage and building a beard of remarkable density.",
    ingredients: ["Black Seed Oil", "Pumpkin Seed Oil", "Vitamin D3", "Caffeine Extract", "Grapeseed Oil"],
    howToUse: "Warm 5-6 drops between palms. Apply to beard from root to tip, massaging vigorously at the skin level. Use daily morning routine.",
    scent: "Dark Oud & Amber, bold and commanding.",
    size: "30ml",
    stock: true,
  },
  {
    id: "muhafiz",
    name: "Muhafiz",
    arabic: "محافظ",
    subtitle: "Protection & Defence",
    tagline: "Guard Your Legacy",
    purpose: "Protection",
    price: 39,
    image: "/assets/product-5.jpeg",
    accent: "#6b8499",
    bg: "#dce5ec",
    description:
      "Muhafiz is your beard's shield. Crafted with UV-protective Carrot Seed oil and antioxidant-rich Sea Buckthorn, it defends against environmental damage, pollution, and harsh weather.",
    ingredients: ["Carrot Seed Oil", "Sea Buckthorn", "Zinc Oxide", "Vitamin C", "Shea Butter"],
    howToUse: "Apply 4-5 drops before going outdoors. Work through beard evenly. Re-apply after swimming or exposure to harsh elements.",
    scent: "Fresh Ocean Breeze & Citrus.",
    size: "30ml",
    stock: true,
  },
];

export type Product = (typeof PRODUCTS)[number];
